### ISSUE TITLE
Polkadot Launch fails with no error

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#103]
After using this script reliably for a while, I suddenly can't start even the relay chain. The script just suddenly exits with no error and no log files created.

This terminal output shows that I haven't hacked the project (except customizing the paths to binaries in my config.json) and then it shows the error.

```
joshy@pop-os:~/ProgrammingProjects/polkadot-launch$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   config.json

no changes added to commit (use "git add" and/or "git commit -a")


joshy@pop-os:~/ProgrammingProjects/polkadot-launch$ yarn start ./config.json 
yarn run v1.22.10
$ yarn build && node dist/index.js ./config.json
$ tsc
2021-06-04 09:08:56  Building chain spec    

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice
  👤 Added Genesis Authority bob
  👤 Added Genesis Authority charlie

⚙ Updating Parachains Genesis Configuration
  ✓ Updated Parachains Configuration [ validation_upgrade_frequency: 1 ]
  ✓ Updated Parachains Configuration [ validation_upgrade_delay: 1 ]

⛓ Adding Genesis Parachains
  ✓ Added Genesis Parachain 1000
⛓ Adding Genesis HRMP Channels

Killing all processes...
Done in 6.12s.
```

**Comment by shawntabrizi** [comment]
Which versions of launch, polkadot, and cumulus are you using?

**Comment by JoshOrndorff** [comment]
Versions:

Polkadot launch: `f161a73a` (latest master as of right now)
Polakdot: `release-v0.9.3`
Moonbeam: `afa835e6` (I know you didn't ask about that, but figured I'd mention it just in case)
Cumulus: `polkadot-v0.9.3`
node-js: `v14.17.0`

**Comment by JoshOrndorff** [comment]
Oops, didn't mean to close this one.

**Comment by clangenb** [comment]
I have a similar problem with the latest master, it does literally nothing.

It simply exits immediately without logs, even if I pass a nonexistent config file.

Polkadot-launch: a63cf06a6accc66d08fd1b3c437200b4a0dbb33f
Node: v14.16.1

**Comment by clangenb** [comment]
nvm, did not see this change that changed the executable's name: https://github.com/paritytech/polkadot-launch/commit/82224520c8de1055d7cf698a1f73d93bf305caac

**Comment by shawntabrizi** [comment]
assuming this is stale
