### ISSUE TITLE
Not creating GenesisState/wasm and not registering for regular parachains?

### ISSUE THREAD

**Issue by jimmychu0807** [paritytech/polkadot-launch#119]
Comparing code:
https://github.com/paritytech/polkadot-launch/blob/master/src/runner.ts#L89-L111 
vs 
https://github.com/paritytech/polkadot-launch/blob/master/src/runner.ts#L114-L155

For "simple parachain" we create the genesis wasm & state, and register it, but not for regular parachain. Why so?

**Comment by shawntabrizi** [comment]
@jimmychu0807 regular parachains are included in the genesis rather than registered via extrinsics. If you look closer you will see this alternate path for registration.
