### ISSUE TITLE
Unable to add `` --telemetry-url "wss://telemetry.polkadot.io/submit 0"`` flag to parachain nodes

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/polkadot-launch#125]
Hi guys, this should reproduce on master, both ubuntu and mac.

Just try to add ``--telemetry-url "wss://telemetry.polkadot.io/submit 0" `` flag to any of the parachain nodes, like https://github.com/paritytech/polkadot-launch/blob/master/config.json#L50
I'm able to add this flag to the relay chain nodes.

I've tried all sorts of combinations of single quotes, double quotes and escape characters, but i'm always getting either:

```
error: Found argument '--charlie ' which wasn't expected, or isn't valid in this context
	Did you mean [32m--[0m[32mcharlie[0m?
	
```

or

```
Invalid value for '--telemetry-url <URL VERBOSITY>...': invalid digit found in string
```

**Comment by ghzlatarev** [comment]
I think I figured it out.

Had to add the flag like so:
```
                    "flags": [
                        "--",
                        "--execution=wasm",
                        "--telemetry-url=wss://telemetry.polkadot.io/submit 0"
                    ]
```
No inner quotes and it launched.

This way if you add a ``console.log(args);`` here https://github.com/paritytech/polkadot-launch/blob/master/src/spawn.ts#L245 it should print:
```
  '--ws-port=9888',
  '--port=31202',
  '--collator',
  '--force-authoring',
  '--tmp',
  '--charlie',
  '--parachain-id=200',
  '--',
  '--chain=/home/georgi/Desktop/workspace/Parity/polkadot-launch/rococo-local-raw.json',
  '--execution=wasm',
  '--telemetry-url=wss://telemetry.polkadot.io/submit 0', 
```

But If you put inner quotes in the telemetry flag it will print: `` "--chain=/home/georgi/Desktop/workspace/Parity/polkadot-launch/rococo-local-raw.json",`` --> double quotes instead of single quotes like all the others.

**Comment by bkchr** [comment]
So this can be closed?
