### ISSUE TITLE
Parachain nodes are not peering with default config

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/polkadot-launch#171]
Using the default config with an additional parachain node, the relay-chain node and the parachain nodes are up and running but the parachain nodes are not peering. If I add the `--force-authoring` flag to the parachain nodes, the parachain starts creating blocks.

**Comment by brunopgalvao** [comment]
Is `--force-authoring` required, according to these docs it is:
- https://docs.substrate.io/tutorials/v3/cumulus/connect-parachain/#start-the-collator-node
- https://github.com/paritytech/cumulus#launch-the-parachain
And according to these it is not:
- https://github.com/paritytech/polkadot-launch/issues/146
- https://github.com/paritytech/polkadot-launch/pull/143

If anyone can shed some light on this that would be great.

**Comment by dharjeezy** [comment]
I am really experiencing this same issue.

**Comment by al3mart** [comment]
polkadot-launch itself will ad the flag `--force-authoring` when we are running one node alone for the parachain. See source [here](https://github.com/paritytech/polkadot-launch/blob/f854c567cedf7f36dacd86faadd49a962ca97d52/src/spawn.ts#L221-L224)

A pair of things to check here then:
- Nodes are connected. We can run as many nodes as we want but if they are not properly connected, they will not produce.
- Check the `paraId` in the state of our para is matching the `paraId` where the wasm and state of the para has been registered on the relay chain. As mention [here](https://github.com/paritytech/polkadot-launch/issues/151#issuecomment-1058533904)

If the configuration doesn't deviates much from a default config these should be one of the few checks to make for the parachain working as expected. For more custom chain specs and set ups the possible points of failure may vary

**Comment by brunopgalvao** [comment]
For parachain node peering to work for me, I had to replace the `id` field in the [config.json](https://github.com/paritytech/polkadot-launch/blob/master/config.json#L43):
```json
"id": "200",
```
with the `chain` field like this:
```json
"chain": "statemine-dev",
```
then my parachain collators peer, otherwise they do not.

Here is my config for reference:
- https://gist.github.com/brunopgalvao/1c694da8c9514a18c51fa68d30ec08e9#file-config-json-L43

**Comment by dharjeezy** [comment]
> For parachain node peering to work for me, I had to replace the `id` field in the [config.json](https://github.com/paritytech/polkadot-launch/blob/master/config.json#L43):
> 
> ```json
> "id": "200",
> ```
> 
> with the `chain` field like this:
> 
> ```json
> "chain": "statemine-dev",
> ```
> 
> then my parachain nodes peer, otherwise they do not.
> 
> Here is my config for reference:
> 
> * https://gist.github.com/brunopgalvao/1c694da8c9514a18c51fa68d30ec08e9#file-config-json-L43

Alright... Thanks so much, will try this out and give you feedback.
