### ISSUE TITLE
Upgrade to polkadot-v0.9.22 breaks polkadot-launch

### ISSUE THREAD

**Issue by haerdib** [paritytech/polkadot-launch#184]
We've recently upgraded to `polkadot-v0.9.22`. Since then, the polkadot-launch script is able to start the relay chain and the first collator, but then it freezes, not continuing to start the second one. The logs of the first collator don't show anything unusual, and manually starting a second one works as well.

To ensure that this is not simply a faulty [commit on our side](https://github.com/integritee-network/parachain/pull/130), I tried to start an [Acala node](https://github.com/AcalaNetwork/Acala), which is also on polkadot-v0.9.22, via polkadot launch, and it froze as well.

Does the `config.json` need an extra input value?

**Comment by pepoviola** [comment]
Hi @haerdib, Are you running from `master`? I think this issue was fixed by #183 .
Thanks!

**Comment by haerdib** [comment]
Yes, that seems to have been the cause. Thanks for the feedback!
