### ISSUE TITLE
Unable to launch js files because polkadot-launch cannot be found

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-launch#194]
Hello, when I install polkadot-launch with npm and global setting I get message -bash: polkadot-launch: command not found
Any known fixes for this? On ubuntu all worked well. 
Laptop macbook pro 15 2016, newest os.
Thank you

**Comment by ilja-khabarov** [comment]
feels like a problem with Yarn. This may help https://stackoverflow.com/questions/40317578/yarn-global-command-not-working
