### ISSUE TITLE
Use polkadot-launch to test Moonbeam

### ISSUE THREAD

**Issue by joelamouche** [paritytech/polkadot-launch#31]
- we need to use the 'ethereum' type for the keyring. How should we go about this? Add a field in the config?
- the setBalance function is called on the relaychain api. Shouldn't it be called on the parachain instead?

**Comment by bkchr** [comment]
Polkadot-launch is not for setting up your parachain. It is for setting up the relay chain and registering the parachains. Anything after this is up to you.

**Comment by joelamouche** [comment]
@shawntabrizi answered my questions:
The setBalance is meant for the relaychain indeed and this is why it has to use sr25519
