### ISSUE TITLE
convert to typescript

### ISSUE THREAD

**Issue by joelamouche** [paritytech/polkadot-launch#43]
Is there any reason this project is not written in typescript?
I'd be happy to take that on

**Comment by pepyakin** [comment]
I think I'd support that. What @shawntabrizi would say?

Before that though I'd prefer https://github.com/paritytech/polkadot-launch/pull/28 to be merged 😄

**Comment by pepyakin** [comment]
FWIW, it's merged now

**Comment by joelamouche** [comment]
OK @shawntabrizi Can I go ahead and convert the code to typescript?

**Comment by shawntabrizi** [comment]
Of course, go for it :)
