### ISSUE TITLE
Polkadot-launch does not wait for relaychain to start

### ISSUE THREAD

**Issue by gregdhill** [paritytech/polkadot-launch#58]
This may be an issue with polkadot{.js} but `ApiPromise` does not wait for the polkadot node to start which crashes this tool on `connect`.

```
2021-02-17 18:08:51          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed

Killing all processes...
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<_Event>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by pepyakin** [comment]
Oh, it certainly used to keep connecting. See also https://github.com/paritytech/polkadot-launch/pull/51#discussion_r569452425

**Comment by joelamouche** [comment]
Is this solved @gregdhill ?

**Comment by vyorkin** [comment]
I've just tried the patch from @gregdhill, it successfully connects to relay-node's websocket port, the only issue is that it just tries to do it too early and produces a few warnings

**Comment by shawntabrizi** [comment]
> tries to do it too early and produces a few warnings

Yeah that is expected. The time it takes to start up a node and the websocket port is variable. Best thing i could think of was just trying to connect until it works.

**Comment by shawntabrizi** [comment]
This should actually be solved by: https://github.com/paritytech/polkadot-launch/pull/92
