### ISSUE TITLE
Doesn't work on Node >15

### ISSUE THREAD

**Issue by wpank** [paritytech/polkadot-launch#60]
Per some struggles from @rphmeier , this doesn't look to work on node versions greater than 14. Should either lock the version or explicitly mention what version to use in the readme.

**Comment by shawntabrizi** [comment]
Is there a root cause why it might not work?

Is it a problem with polkadot js?

**Comment by wpank** [comment]
I'm not too sure on the cause exactly. Also don't remember exactly what didn't work (and it may have inadvertently gotten fixed since then).

It was easily reproducible in Feb though with node 15. My guess would be some of the process spawning apis.

**Comment by rphmeier** [comment]
I remember I was getting websocket errors - we failed to initiate the connection to the endpoint

**Comment by JoshOrndorff** [comment]
Title should be `Doesn't work on Node >= 15` greater than or equal to.

**Comment by JoshOrndorff** [comment]
I also reported this in #90. This issue came first, but that one is more descriptive, so might make sense to keep that one. Up to you guys.

**Comment by shawntabrizi** [comment]
I agree, #90 should be used to track this moving forward.
