### ISSUE TITLE
Make util functions promises

### ISSUE THREAD

**Issue by joelamouche** [paritytech/polkadot-launch#65]
For better reliance, we should make
- registerParachain
- setBalance
- startCollator
- and the // Then launch each parachain part of index

functions that return a promise that resolves when the process is done.
Checkout how I implemented it here: https://github.com/paritytech/polkadot-launch/pull/55/files

I volunteer to make these changes

**Comment by joelamouche** [comment]
@pepyakin @shawntabrizi  ?

**Comment by joelamouche** [comment]
@pepyakin @shawntabrizi Did you get any chance to read this?

**Comment by joelamouche** [comment]
I don't think there is any downside in making those function return promises

**Comment by bkchr** [comment]
Yeah, just do it. :)

**Comment by shawntabrizi** [comment]
yeah go ahead :)

**Comment by joelamouche** [comment]
cool :)

**Comment by joelamouche** [comment]
This is now merged into master and can be closed
