### ISSUE TITLE
Register parachains at genesis, rather than via sudo

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#66]
The paras pallet has a genesis config that allows paras to be registered from the very beginning.

https://github.com/paritytech/polkadot/blob/c55af37064b49719694e0e72aabfdac9e99fb1d2/runtime/parachains/src/paras.rs#L306

This would avoid having to wait for 20 block to roll by before your collators start collating.

**Comment by JoshOrndorff** [comment]
Oh interesting. Even though there is that genesis config, it isn't exposed in the rococo runtime. Is that on purpose @bkchr 

https://github.com/paritytech/polkadot/blob/master/runtime/rococo/src/lib.rs#L217

**Comment by bkchr** [comment]
No, probably just overseen it.
