### ISSUE TITLE
Schema version for config file

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#89]
The config file should have a field for schema version. When polkadot launch is run,it first checks the schema version to see if it knows how to interpret the config file. If not, fail with a reasonable error message. This will help users avoid confusion when they run an old version of polkadot launch with a new config file or vice versa.

**Comment by shawntabrizi** [comment]
the `check` file should basically do the same.

**Comment by JoshOrndorff** [comment]
What is the `check` file?

**Comment by shawntabrizi** [comment]
https://github.com/paritytech/polkadot-launch/blob/master/src/check.ts

**Comment by JoshOrndorff** [comment]
Oh nice. Didn't realize you had it already.
