### ISSUE TITLE
`ERR_UNHANDLED_REJECTION` on node.js >= 15

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#90]
I'm trying to run this tool with the latest `rococo-v1` branches.

Polkadot: 127eb17a25bbe2a9f2731ff11a65d7f8170f2373
Cumulus: da4c3bac6e9584e65740ef5db4dbd2c31c1a91db

But it fails to start the chain(s) with this output.

```
$ yarn start ./config.json 
yarn run v1.22.5
$ yarn build && node dist/index.js ./config.json
$ tsc
2021-04-28 16:21:05  Building chain spec    

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice
  👤 Added Genesis Authority bob
  👤 Added Genesis Authority charlie
  👤 Added Genesis Authority dave

⚙ Updating Parachains Genesis Configuration
  ✓ Updated Parachains Configuration [ validation_upgrade_frequency: 1 ]
  ✓ Updated Parachains Configuration [ validation_upgrade_delay: 1 ]

⛓ Adding Genesis Parachains
  ✓ Added Genesis Parachain 200
  ✓ Added Genesis Parachain 300

2021-04-28 16:21:13  Building chain spec    
2021-04-28 16:21:20  Took active validators from set with wrong size    
2021-04-28 16:21:20  Took active validators from set with wrong size    
Starting alice...
Starting bob...
Starting charlie...
Starting dave...
2021-04-28 16:21:20          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed

Killing all processes...
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<_Event>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The only thing I've changed in any of the repos is the paths to my binaries in the config.json file.

**Comment by JoshOrndorff** [comment]
Looks like the error comes from here on the polkadot side https://github.com/paritytech/polkadot/blob/rococo-v1/runtime/parachains/src/util.rs#L54

**Comment by al3mart** [comment]
Faced the same warning today when building raw chain specs (not using polkadot launch, though), I don't think that is the origin of the crash as, even after prompting the warning my chainspec was successfully built.

**Comment by shawntabrizi** [comment]
Joshy reported in chat that downgrading to Node v14 solved this problem.

Not sure what is causing it though, would be very happy to get some insight from a JS god

**Comment by shawntabrizi** [comment]
> The unhandledRejection event is emitted whenever a promise is rejected and no error handler is attached to the promise within a turn of the event loop. Starting from Node.js 15, the default mode for unhandledRejection has been changed to throw from warn. In throw mode, if an unhandledRejection hook is not set, the unhandledRejection is raised as an uncaught exception.

https://betterprogramming.pub/whats-new-in-node-js-15-fc24e87e2590
