### ISSUE TITLE
Support custom session length in config.json

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#91]
Since https://github.com/paritytech/polkadot/pull/2167, polkadot has supported a custom session length in the chain spec file. However this property is _not_ part of the `runtime_genesis_config`, which means it can't be modified by the mechanism introduced in #88.

This issue is to support custom session length in polkadot-launch's `config.json`. I can imagine two potential solutions.
1. Extend polkadot-launch to support it
2. Modify polkadot so it goes in the normal genesis config (but I'm guessing there is a good reason it wasn't put there to begin with?).

**Comment by shawntabrizi** [comment]
@JoshOrndorff i think it should be easy enough to support it, but can you describe how to do it

**Comment by JoshOrndorff** [comment]
Yeah exactly. The output of `polkadot build-spec --chain rococo-local` is

```json
{
  "name": "Rococo Local Testnet",
  "id": "rococo_local_testnet",
  "chainType": "Local",
  "bootNodes": [],
  "telemetryEndpoints": null,
  "protocolId": "dot",
  "properties": null,
  "forkBlocks": null,
  "badBlocks": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
    "runtime": {
      "runtime_genesis_config": {
        // Content elided
        // All of this stuff is already handled properly
      },
      // This is the different one that I'd like to set
      "session_length_in_blocks": 10
    }
  }
}
```
