### ISSUE TITLE
Support the `chain` field for parachains just like for Relay chain

### ISSUE THREAD

**Issue by JoshOrndorff** [paritytech/polkadot-launch#96]
When configuring the relay chain the user can put a field in the config like `"chain": "rococo-local"`. This indicates a starting point for the relay chain spec that will be customized.

This would be very useful on the parachain side too. Even if no customization happens on the para side, it would still be useful to specify `"chain": "local"`.

Currently Polkadot Launch does not specify any specific chain which is the same as specifying `--chain ""`. This is not convenient for Moonbeam, where we reserve `""` to indicate Moonbeam mainnet (just like Polkadot does). Currently we hit [this line](https://github.com/PureStake/moonbeam/blob/f655a44b142524ca10f40fe4fb636abbbd964177/node/src/command.rs#L58-L62) in moonbeam, which means we have to hack the moonbeam node to disable that line when we want to use Polkadot Launch.

Being able to specify which chain spec to syncing in the launch config would solve this problem

**Comment by JoshOrndorff** [comment]
I think this is actually working already, and I just didn't know it when I opened the issue.

**Comment by GopherJ** [comment]
yes I also realized this yesterday.  Thanks
